channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.2.1
  - blosc=1.20.1
  - bqplot=0.12.18
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - ca-certificates=2020.11.8
  - certifi=2020.11.8
  - cffi=1.14.4
  - chardet=3.0.4
  - charls=2.1.0
  - cloudpickle=1.6.0
  - cryptography=3.2.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2.30.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - freetype=2.10.4
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.3
  - icu=64.2
  - idna=2.10
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=3.1.1
  - importlib_metadata=3.1.1
  - intel-openmp=2019.4
  - ipydatawidgets=4.1.0
  - ipykernel=5.3.4
  - ipympl=0.5.8
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ipyvolume=0.6.0a6
  - ipywebrtc=0.5.0
  - ipywidgets=7.5.1
  - jinja2=2.11.2
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=5.2.0
  - jupyter_core=4.7.0
  - jupyter_server=1.0.8
  - jupyterlab=2.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - lcms2=2.11
  - lerc=2.2
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=11.0.0
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.66.3
  - libiconv=1.16
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libzopfli=1.0.3
  - llvm-openmp=11.0.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.1.5
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1h
  - packaging=20.7
  - pandas=1.1.3
  - pandoc=2.11.2
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.3.1
  - prometheus_client=0.9.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.7.2
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.8
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pythreejs=2.2.1
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=5.0.1
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.25.0
  - scikit-image=0.17.2
  - scipy=1.5.3
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - sip=4.19.8
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.34.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tifffile=2020.11.26
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=4.3.3
  - traittypes=0.2.1
  - urllib3=1.25.11
  - voila=0.2.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.0
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.3
  - zfp=0.5.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
